from zxcvbn import zxcvbn
from faker import Faker
import random
import csv
import io
import json

fake = Faker()

def analyze_password(password: str) -> dict:
    """
    Analyzes password strength using zxcvbn.
    Returns score (0-4), crack times, and feedback.
    """
    if not password:
        return {"score": 0, "feedback": {"warning": "Password cannot be empty", "suggestions": []}}
        
    result = zxcvbn(password)
    
    return {
        "score": result['score'],
        "crack_times": result['crack_times_display'],
        "feedback": result['feedback'],
        "guesses": result['guesses']
    }

def generate_decoy(doc_type: str) -> dict:
    """
    Generates a decoy document based on type.
    Returns filename and content (bytes).
    types: 'financial', 'corporate', 'medical', 'personal'
    """
    
    if doc_type == 'financial':
        # Generate Fake Financial CSV
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Transaction ID', 'Date', 'Description', 'Amount', 'Status', 'Account'])
        
        for _ in range(100):
            writer.writerow([
                fake.uuid4()[:8],
                fake.date_this_year(),
                fake.bs().title(),
                round(random.uniform(100.00, 50000.00), 2),
                random.choice(['Completed', 'Pending', 'Failed']),
                fake.iban()
            ])
            
        return {
            "filename": "financial_report_Q3.csv",
            "mimetype": "text/csv",
            "content": output.getvalue().encode('utf-8')
        }
        
    elif doc_type == 'corporate':
        # Generate Fake Employee List CSV
        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow(['Employee ID', 'Name', 'Job Title', 'Department', 'Email', 'Phone'])
        
        for _ in range(50):
            writer.writerow([
                fake.random_number(digits=5),
                fake.name(),
                fake.job(),
                random.choice(['HR', 'Engineering', 'Sales', 'Marketing', 'Executive']),
                fake.company_email(),
                fake.phone_number()
            ])
            
        return {
            "filename": "employee_directory_confidential.csv",
            "mimetype": "text/csv",
            "content": output.getvalue().encode('utf-8')
        }

    elif doc_type == 'personal':
        # Generate Fake Diary Entry
        content = f"CONFIDENTIAL DIARY - {fake.date()}\n\n"
        for _ in range(5):
            content += f"{fake.time()}: {fake.paragraph(nb_sentences=5)}\n\n"
            
        return {
            "filename": "personal_diary.txt",
            "mimetype": "text/plain",
            "content": content.encode('utf-8')
        }

    else:
        # Default/Generic
        return {
            "filename": "readme.txt",
            "mimetype": "text/plain",
            "content": b"This is a decoy file generated by Cryptaris."
        }
