import { useState } from 'react';
import { FileText, Briefcase, User, Download, Shield } from 'lucide-react';
import FeatureLayout from '@/components/FeatureLayout';
import { Button } from '@/components/ui/button';
import { generateDecoy } from '@/lib/api';
import { useToast } from '@/hooks/use-toast';

const DecoyGenerator = () => {
    const [loading, setLoading] = useState(false);
    const { toast } = useToast();

    const handleGenerate = async (type: string) => {
        setLoading(true);
        try {
            const resultBlob = await generateDecoy(type);

            // Create download link
            const url = window.URL.createObjectURL(resultBlob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `decoy_${type}_${Date.now()}.csv`; // Default extension
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            window.URL.revokeObjectURL(url);

            toast({
                title: "Decoy Generated",
                description: `A fake ${type} document has been created.`
            });
        } catch (error: any) {
            toast({
                title: "Generation Failed",
                description: error.message,
                variant: "destructive"
            });
        } finally {
            setLoading(false);
        }
    };

    return (
        <FeatureLayout
            title="AI Decoy Generator"
            description="Create realistic fake documents to provide plausible deniability. If forced to decrypt data, offer these decoys instead."
            icon={Shield}
            backLink="/"
        >
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-4xl mx-auto mt-8">
                <div className="glass-card p-6 flex flex-col items-center text-center hover:bg-primary/5 transition-colors cursor-pointer border-primary/20" onClick={() => handleGenerate('financial')}>
                    <div className="p-4 rounded-full bg-blue-500/10 text-blue-500 mb-4">
                        <FileText size={32} />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">Financial Records</h3>
                    <p className="text-sm text-muted-foreground mb-6">
                        Fake bank statements, transaction logs, and asset reports.
                    </p>
                    <Button variant="outline" className="w-full" disabled={loading}>
                        Generate Financial Decoy
                    </Button>
                </div>

                <div className="glass-card p-6 flex flex-col items-center text-center hover:bg-primary/5 transition-colors cursor-pointer border-primary/20" onClick={() => handleGenerate('corporate')}>
                    <div className="p-4 rounded-full bg-purple-500/10 text-purple-500 mb-4">
                        <Briefcase size={32} />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">Corporate Data</h3>
                    <p className="text-sm text-muted-foreground mb-6">
                        Fake employee lists, internal memos, and project roadmaps.
                    </p>
                    <Button variant="outline" className="w-full" disabled={loading}>
                        Generate Corporate Decoy
                    </Button>
                </div>

                <div className="glass-card p-6 flex flex-col items-center text-center hover:bg-primary/5 transition-colors cursor-pointer border-primary/20" onClick={() => handleGenerate('personal')}>
                    <div className="p-4 rounded-full bg-pink-500/10 text-pink-500 mb-4">
                        <User size={32} />
                    </div>
                    <h3 className="text-lg font-semibold mb-2">Personal Diary</h3>
                    <p className="text-sm text-muted-foreground mb-6">
                        Fake private journal entries and personal notes.
                    </p>
                    <Button variant="outline" className="w-full" disabled={loading}>
                        Generate Personal Decoy
                    </Button>
                </div>
            </div>

            <div className="mt-12 text-center text-sm text-muted-foreground max-w-2xl mx-auto">
                <p>
                    <strong>Note:</strong> These files are generated by AI using the Faker library.
                    They contain no real data but are structured to look authentic to a casual observer.
                </p>
            </div>
        </FeatureLayout>
    );
}

export default DecoyGenerator;
